
// disclaimer: generated by AI
/**
 * Format a number as currency.
 * @param amount - number to format
 * @param currency - currency code, default USD
 * @param locale - locale string, default en-US
 * @returns formatted currency string
 */
export function formatCurrency(
  amount: number,
  currency: string = 'USD',
  locale: string = 'en-US'
): string {
  if (amount == null || isNaN(amount)) return '';
  
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}
